version: '3'
services:
  app:
    container_name: ejemploFullPlay
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/root
    ports:
      - "8100:9000"
    stdin_open: true
  